// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18408
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace FormualSpecs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class PPLFeature : Xunit.IUseFixture<PPLFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "PPL.feature"
#line hidden
        
        public PPLFeature()
        {
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "PPL", "Update the TelesProfiles database with load profile coefficients.\r\nThe inputs wil" +
                    "l an arbitrary date range, and a weather forecast ID.\r\nThe output will be a set " +
                    "of coefficients for the given date range,\r\nwritten to specified table(s)", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void SetFixture(PPLFeature.FixtureData fixtureData)
        {
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.Extensions.TheoryAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "PPL")]
        [Xunit.TraitAttribute("Description", "Calculate coefficient for single interval")]
        [Xunit.Extensions.InlineDataAttribute("50", "1.561", new string[0])]
        [Xunit.Extensions.InlineDataAttribute("60", "1.5247", new string[0])]
        [Xunit.Extensions.InlineDataAttribute("70", "1.5421", new string[0])]
        [Xunit.Extensions.InlineDataAttribute("80", "1.6623", new string[0])]
        public virtual void CalculateCoefficientForSingleInterval(string temperature, string coefficient, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Calculate coefficient for single interval", exampleTags);
#line 8
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value"});
            table1.AddRow(new string[] {
                        "HIGH_1",
                        "50.4741"});
            table1.AddRow(new string[] {
                        "HIGH_2",
                        "64.5280"});
            table1.AddRow(new string[] {
                        "HIGH_3",
                        "77.3043"});
            table1.AddRow(new string[] {
                        "HIGH_4",
                        "99999"});
            table1.AddRow(new string[] {
                        "COEFF_1",
                        "-0.0204"});
            table1.AddRow(new string[] {
                        "COEFF_2",
                        "-0.0028"});
            table1.AddRow(new string[] {
                        "COEFF_3",
                        "0.0055"});
            table1.AddRow(new string[] {
                        "COEFF_4",
                        "0.0297"});
            table1.AddRow(new string[] {
                        "REGRESSION_CONSTANT",
                        "2.5810"});
#line 9
 testRunner.Given("the following coefficients and constants:", ((string)(null)), table1, "Given ");
#line 21
 testRunner.And(string.Format("the temperature is {0} degF", temperature), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 22
 testRunner.When("the coefficient request is made", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 23
 testRunner.Then(string.Format("the result should be {0}", coefficient), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                PPLFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                PPLFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
